apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
rules:
- apiGroups: [""]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  resources:
  - pods
  - services
- apiGroups: ["extensions", "apps" ]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  resources:
  - deployments
  - replicasets
  - statefulsets  
- apiGroups: ["batch", "extensions"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  resources:
  - jobs
  - cronjobs
