apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-role
rules:
- apiGroups: [""]
  verbs: [get list watch]
  resources:
  - pods
  - persistentvolumeclaims
  - persistentvolumes
  - services
- apiGroups: ["extensions", "apps" ]
  verbs: [get list watch]
  resources:
  - deployments  
- apiGroups: ["batch", "extensions"]
  verbs: [list]
  resources:
  - jobs
  - cronjobs