apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-role
  namespace: default
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - deployments
  - replicasets
  verbs:
  - get
  - delete
  - list
  - watch
- apiGroups: ["batch", "extensions"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
